SAMPLE_SETS = ['en', 'es', 'fr', 'id']
SEQUENCE_LENGTH = 20
EMBEDDING_DIM = 300

GSMaP_USERNAME = ''
GSMaP_PASSWORD = ''

POSTGRESQL_HOST = '127.0.0.1'
POSTGRESQL_PORT = 5432
POSTGRESQL_USER = ''
POSTGRESQL_PASSWORD = ''

TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''

EXPORT_DIR = 'model_exports'